_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", include("home.urls")),
    path("productos/", include("productos.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("carrito/", include("carrito.urls")),
]

######### PARA IMAGENES

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
## Con esa importación, maneja archivos estáticos
from django.urls import path
    #! Include sirve para traer URLS de las apps
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from . import views

app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_request, name="login"),
    path("logout/", LogoutView.as_view(template_name="Home/logout.html"), name="logout"),
    path("about/", TemplateView.as_view(template_name="Home/about.html"), name="about"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()
### Con esto, le agrego los statics files al URL PATTERNS
### Ahora puedo llamar o manipular los archivos staticos
### Desde el HTML, desde los Templates

apps/usuarios/urls.py
from django.urls import path
    #! Include sirve para traer URLS de las apps
from django.conf import settings
from django.conf.urls.static import static
from .views import home, crear_usuarios, buscar_usuarios

app_name = "usuarios"

urlpatterns = [
    path("", home, name="home"),
    path("crear_usuarios", crear_usuarios, name="crear_usuarios"),
    path('buscar_usuarios/', buscar_usuarios, name='buscar_usuarios'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/models.py
from django.db import models

class Usuario(models.Model):
    nombre = models.CharField(max_length=20, null=False)
    apellido = models.CharField(max_length=20, null=False)
    correo = models.CharField(max_length=50, null=False)
    edad = models.IntegerField()
    def __str__(self):
        return f'{self.nombre} {self.apellido}. {self.correo}. Tiene {self.edad} años'
    

apps/usuarios/forms.py
from django import forms
from .models import Usuario

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = "__all__"

apps/usuarios/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from .forms import UsuarioForm
from .models import Usuario
# Create your views here.

def home(request):
    usuarios_registrados = Usuario.objects.all()
    contexto = {"usuarios": usuarios_registrados}
    return render(request, "usuarios/index.html", contexto)

####### Formulario Crear Usuarios###
def crear_usuarios(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = UsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("usuarios:home")
    else:
        form = UsuarioForm()
    return render(request, "usuarios/crear_usuarios.html", {"form": form})

####### Busqueda de Usuarios ####
def buscar_usuarios(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        # Obtener el término de búsqueda del formulario
        termino_busqueda = request.POST.get('termino_busqueda')
        # Realizar la búsqueda en la base de datos
        usuario = Usuario.objects.filter(nombre__icontains=termino_busqueda)
        # Pasar los resultados de la búsqueda al contexto
        context = {'usuarios': usuario}
        return render(request, 'usuarios/buscar_usuarios.html', context)
    else:
        return render(request, 'usuarios/buscar_usuarios.html')

apps/usuarios/templates/usuarios/buscar_usuarios.html
{% extends 'Home/base.html' %}
{% load static %}

{% block BODY %}
    <!-- Buscar Usuarioo -->
    <form class="text-center " method="post">
        {% csrf_token %}
        <input type="text" name="termino_busqueda" placeholder="Busca un usuario...">
        <button type="submit">Encuéntra el usuario</button>
        <p></p>
    </form>

    <!-- Resultado Busqueda -->
    <div class="row gx-4 gx-lg-5 justify-content-center">
        {% if usuarios %}
            {% for usuario in usuarios %}
              <div class="col-sm-4 col-md-4 col-lg-3 border">
                <style> .border{border: 1px solid black; border-radius: 15px;}</style>
                <h3 class="text-center ">{{usuario.nombre}} {{usuario.apellido}}</h3>
                <h6>Edad: {{usuario.edad}} años</h6>
                <h6>Correo: {{usuario.correo}}</h6>
              </div>
            {% endfor %}
        {% else %}
        <p></p>
        <h3 class="text-center text-danger ">No se encontraron resultados. <br>Favor ingresa un usuario.</h3>
        {% endif %}
    </div>
    <p></p>
    <a class="text-center" href="{% url 'usuarios:home' %}">Volver atras</a>
    <a class="text-center" href="{% url 'Home:home' %}">Volver al menú principal</a>

{% endblock BODY %}

apps/usuarios/templates/usuarios/crear_usuarios.html
{% extends 'Home/base.html' %}

{% block BODY %}
    <h1 class="text-center">INGRESA UN NUEVO USUARIO</h1>
    <!-- Etiqueta Formulario -->
    <div class="bg-black text-warning formulario text-center ">
        <style>
            .formulario{
                padding: 50px;
                width: 95%;
                margin: 25px;
            }
        </style>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}} 
            <button class="btn btn-danger" type="submit">Guardar</button>
    </div>

    <a class="text-center" href="{% url 'usuarios:home' %}">Volver atras</a>
    <a class="text-center" href="{% url 'Home:home' %}">Volver al menú principal</a>
{% endblock BODY %}

apps/usuarios/templates/usuarios/index.html
{% extends 'Home/base.html' %}
{% load static %}

{% block BODY %}
    <!-- Content Row-->
    <div class="row justify-content-evenly">
        {% if user.is_staff %}
        <div class="col-sm-4 col-md-4 col-lg-3">
            <a href="{% url 'admin:index' %}">
                <img class="text-center img-fluid img-thumbnail rounded mx-auto d-block w-75" src="{% static 'Home/img/panel.png' %}"></img>
            </a>
            <h3 class="text-center">Panel de Administración</h3>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-3">
            <a href="{% url 'Home:register' %}">
                <img class="img-fluid img-thumbnail rounded mx-auto d-block w-75" src="{% static 'Home/img/iconoUsuario.jpg' %}"></img>
            </a>
            <h3 class="text-center">Crear un usuario</h3>
        </div>
        {% endif %}
        <div class="col-sm-4 col-md-4 col-lg-3 ">
            <a href="{% url 'Home:login' %}">
                <img class="img-fluid img-thumbnail rounded mx-auto d-block w-75" src="{% static 'Home/img/iniciarSesion.png' %}"></img>
            </a>
            <h3 class="text-center">Iniciar sesión</h3>
        </div>
        <div class="col-sm-4 col-md-4 col-lg-3 ">
            <a href="{% url 'usuarios:buscar_usuarios' %}">
                <img class="img-fluid img-thumbnail rounded mx-auto d-block w-75" src="{% static 'Home/img/buscarUsuario.png' %}"></img>
            </a>
            <h3 class="text-center">Buscar un usuario</h3>
        </div>
    </div>
{% endblock BODY %}