_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", include("home.urls")),
    path("productos/", include("productos.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("carrito/", include("carrito.urls")),
]

######### PARA IMAGENES

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/carrito/urls.py
from django.urls import path
    #! Include sirve para traer URLS de las apps
from . import views

app_name = "carrito"

urlpatterns = [
    path("", views.carrito, name="index"),
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar_producto"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar_producto"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar_producto"),
    path("limpiar/", views.limpiar_carrito, name="limpiar_carrito"),
    path("enviar/", views.enviar_correo, name="enviar_correo"),
] 

apps/home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
## Con esa importación, maneja archivos estáticos
from django.urls import path
    #! Include sirve para traer URLS de las apps
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from . import views

app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_request, name="login"),
    path("logout/", LogoutView.as_view(template_name="Home/logout.html"), name="logout"),
    path("about/", TemplateView.as_view(template_name="Home/about.html"), name="about"),
    path("register/", views.register, name="register"),
]

urlpatterns += staticfiles_urlpatterns()
### Con esto, le agrego los statics files al URL PATTERNS
### Ahora puedo llamar o manipular los archivos staticos
### Desde el HTML, desde los Templates

apps/productos/urls.py
from django.urls import path
    #! Include sirve para traer URLS de las apps
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from . import views

app_name = "productos"

urlpatterns = [
    path("", views.index, name="index"),
    # path("", TemplateView.as_view(template_name="productos/index.html"), name="home"),

    path("ingresar_productos", views.ingreso_productos, name="ingresar_productos"),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),
    ## Categorias
    path("categoria/list/", views.CategoriaList.as_view(), name="categoria_list"),
    path('categoria/create', views.CategoriaCreate.as_view(), name="categoria_create"),
    path('categoria/details/<int:pk>', views.CategoriaDetail.as_view(), name='categoria_details'),
    path('categoria/update/<int:pk>', views.CategoriaUpdate.as_view(), name='categoria_update'),
    path('categoria/delete/<int:pk>', views.CategoriaDelete.as_view(), name='categoria_delete'),

    ### Productos
    path("productos/list/", views.ProductosList.as_view(), name="productos_list"),
    path('productos/create', views.ProductosCreate.as_view(), name="productos_create"),
    path('productos/details/<int:pk>', views.ProductosDetail.as_view(), name='productos_details'),
    path('productos/update/<int:pk>', views.ProductosUpdate.as_view(), name='productos_update'),
    path('productos/delete/<int:pk>', views.ProductosDelete.as_view(), name='productos_delete'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/urls.py
from django.urls import path
    #! Include sirve para traer URLS de las apps
from django.conf import settings
from django.conf.urls.static import static
from .views import home, crear_usuarios, buscar_usuarios

app_name = "usuarios"

urlpatterns = [
    path("", home, name="home"),
    path("crear_usuarios", crear_usuarios, name="crear_usuarios"),
    path('buscar_usuarios/', buscar_usuarios, name='buscar_usuarios'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
    ### Este sirve para ingresar
from django.contrib.auth.models import User
    ### Este sirve para crear el usuario

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password", "email")
        ## Los campos los puedo ver en la BD
        ## En la parte auth_usr
        widgets = {
            "username": forms.TextInput(attrs={"class":"form-control"}),
            "email": forms.TextInput(attrs={"class":"form-control"}),
            "password": forms.PasswordInput(attrs={"class":"form-control"}),
        }

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        help_text = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class":"form-control"}),
            "email": forms.TextInput(attrs={"class":"form-control"}),
            "password1": forms.PasswordInput(attrs={"class":"form-control"}),
            "password2": forms.PasswordInput(attrs={"class":"form-control"}),
        }

apps/home/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate

from . import forms

# Create your views here.
def home(request): 
    return render(request, "home/index.html")  

### Login
def login_request(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password")
            user = authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request, "Home/index.html", {"mensaje": "Inicio de sesión correcto"})
    else:
        form = forms.CustomAuthenticationForm()
    return render(request, "home/login.html", {"form":form})

### Registro
from django.contrib.admin.views.decorators import staff_member_required
@staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            form.save()
            return render(request, "Home/index.html", {"mensaje": "Registro de Usuario exitoso"})
    else:
        form = forms.CustomUserCreationForm()
    return render(request, "home/register.html", {"form":form})

apps/home/templates/home/about.html
{% extends 'Home/base.html' %}
{% load static %}


{% block TITULO %}
<h1>Sobre Mí</h1>
{% endblock TITULO %}

{% block BODY %}
<div>
    <div class="card w-25 m-2 m-auto">
        <div class="card-body bg-black">
            <h2 class="card-title text-light text-center">Eduardo Ureta Campos</h2>
            <div class="text-center">
                <h4 class="card-text text-black badge bg-warning">Tengo 29 años</h4>
                <h4 class="card-text text-light badge bg-primary">Equipo de Fútbol: Universidad de Chile</h4>
                <h4 class="card-text text-black badge bg-danger">Ing. Computación e Informática</h4>
                <h4 class="card-text text-black badge bg-success ">UNAB</h4>
            </div>
            <div class="text-center">
                <h4 class="card-text text-black badge bg-light">Desarrollo Web</h4>
                <h4 class="card-text text-black badge bg-info">JavaScript</h4>
                <h4 class="card-text text-black badge bg-primary">React JS</h4>
            </div>
            <div class="text-center">
                <h4 class="card-text text-light badge bg-success ">Metodología Ágiles</h4>
                <h4 class="card-text text-black badge bg-warning">SQL</h4>
                <h4 class="card-text text-black badge bg-warning">Python</h4>
                <h4 class="card-text text-black badge bg-danger">Back End JS</h4>
            </div>
            <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{% static '/Home/img/edu.png' %}" alt="Imagen">
        </div>
        <div class="card-footer text-end">
            <a href="{% url 'Home:home' %}" class="btn btn-dark btn-sm">Volver al Home</a>
        </div>
        
    </div>
</div>


{% endblock BODY %}

apps/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Almacen Los Tios ~ Los mejores productos</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'Home/assets/favicon.png' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'Home/css/styles.css' %}" rel="stylesheet" />
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

</head>
<body class="row fondo font-roboto">
    <style> 
        .fondo{
            background-image: linear-gradient(to right bottom, #dee3ea, #c4d3d8, #aec3c0, #a0b1a4, #9b9d89);
        }
        .font-roboto{
            font-family: 'Roboto', sans-serif;
        }
    </style>
    <!-- Responsive navbar-->
    {% include 'Home/navbar.html' %}

    <div class="text-center text-bg-dark text-warning ">
    {% block TITULO %}
        
    {% endblock TITULO %}
    </div>

    <div>
        {% block BODY %}

        {% endblock BODY %}
    </div>
        <!-- Footer-->
        {% include 'Home/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Home/js/scripts.js' %}"></script>

</body>
</html>

apps/home/templates/home/card.html
<div>
    <div class="card h-100 m-2">
        <div class="card-body bg-black">
            <h2 class="card-title text-light">{{card}} </h2>
            <h6 class="card-text text-warning">{{card_categoria}}</h6>
            <h3 class="card-text text-warning text-center">${{card_precio}}</h3>
            <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{{card_imagen}}" alt="Imagen"></img>
        </div>
        <a href="{% url 'carrito:agregar_producto' producto.id %}" class="btn btn-primary">Agregar al carrito</a>
    </div>
</div>

apps/home/templates/home/carrusel.html
{% load static %}
<div class="container">
    <h1 class="text-center">NUESTROS PRODUCTOS</h1>
    <div class="row justify-content-center ">
        <div id="carouselExampleCaptions" class="carousel slide col-sm-4 col-md-4 col-lg-3" data-bs-ride="carousel">
            <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'Home/img/jugo.png' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h3>Jugos y Bebidas</h3>
                <p>¿Deseas un refresco?</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'Home/img/abarrotes.png' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h3>Abarrotes</h3>
                <p>Pastas, arroz, artículos para tu despensa</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'Home/img/alcohol.png' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                <h3>Alcohol</h3>
                <p>Para tus noches de fiestas</p>
                </div>
            </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        </div>
        <div id="carouselExampleCaptions" class="carousel slide col-sm-4 col-md-4 col-lg-3 " data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'Home/img/lacteos.png' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                      <h3 class="text-dark">Lácteos</h3>
                      <p>Variedad para el desayuno u once</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'Home/img/frutasverduras.png' %}" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                      <h3>Frutas y Verduras</h3>
                      <p>Por una alimentación sana</p>
                    </div>
                  </div>
              <div class="carousel-item">
                <img src="{% static 'Home/img/snack.png' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                  <h3 class="text-dark">Snack</h3>
                  <p>Para acompañar tus tragos</p>
                </div>
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
    </div>
</div>

apps/home/templates/home/footer.html
<footer class="py45 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-warning">Eduardo Ureta</p></div>
</footer>

apps/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block BODY %}
    {% if user.is_authenticated %}
        <h6 class="text-center text-bg-dark text-warning  ">{{mensaje}}</h6>
    {% endif %}

    {% include 'home/tiendas.html' %}
    <p></p>
    {% include 'home/carrusel.html' %}

    <div class="container text-center">
        <h3>Contactate con nosotros por WhatsApp</h3>
        <div class="d-flex justify-content-center align-items-center">
            <a href="https://wa.me/56994901217" target="_blank">
                <img class="img-fluid whatsapp" src="{% static 'Home/img/wsp.png' %}">
                <style>.whatsapp{width: 20%;}</style>
            </a>
        </div>
    </div>

    <div class="nav-item text-center">
        <a class="nav-link text-dark" href="{% url 'Home:about' %}">Por último, aquí puedes saber sobre mí</a>
    </div>
    <p></p>
    <p></p>
    <p></p>
{% endblock BODY %}

apps/home/templates/home/login.html
{% extends 'Home/base.html' %}
    
{% block TITULO %}
    <h1>Iniciar Sesión</h1>
{% endblock TITULO %}

{% block BODY %}
    <form action="" method="post" class="formulario">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success "> Iniciar Sesión </button>
    </form>
    <style>
        .formulario {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        }
        input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;
            transition: background-color 0.3s;
        }
        .btn:hover {
            background-color: #45a049;
        }
    </style>
    <br>

    
{% endblock BODY %}

apps/home/templates/home/logout.html
{% extends 'Home/base.html' %}

{% block TITULO %}
    <div class="fs-3 fst-italic text-center">
        <p>Has cerrado sesión</p>
    </div>
{% endblock TITULO %}
    >
{% block BODY %}
    <h3 class="text-center ">Vuelve Pronto :) </h3
{% endblock BODY %}

apps/home/templates/home/navbar.html
{% load static %}

<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container px-5 ">
        <a class="navbar-brand text-warning" href="#!">Almacén Los Tios</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item text-center"><a class="nav-link text-light" aria-current="page" href="{% url 'Home:home' %}">Inicio</a></li>
                <li class="nav-item text-center"><a class="nav-link text-light" href="{% url 'productos:index' %}">Productos</a></li>
                <li class="nav-item text-center"><a class="nav-link text-light" href="{% url 'usuarios:home' %}">Portal Usuarios</a></li>
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li class="nav-item"></li><a href="{% url 'productos:categoria_create' %}" class="nav-link text-light text-center">Crear Categorias</a></li>                     
                        <li class="nav-item"></li><a href="{% url 'productos:categoria_list' %}" class="nav-link text-light text-center">Listar Categorias</a></li>
                        <li class="nav-item"></li><a href="{% url 'productos:productos_create' %}" class="nav-link text-light text-center">Crear Productos</a></li>                     
                        <li class="nav-item"></li><a href="{% url 'productos:productos_list' %}" class="nav-link text-light text-center">Listar Productos</a></li>
                    {% endif %}
                    <li class="nav-item text-center"><a class="nav-link text-light"> | </a></li>
                    {% if user.vendedor.avatar.url %}
                        <li class="nav-item text-center">
                            <img src="{{user.vendedor.avatar.url}}" alt="" style="height: 30px;"></img>
                        </li>
                    {% endif %}
                    <li class="nav-item text-center"><a class="nav-link text-warning" href="#!">{{user.username}}</a></li>
                    <li class="nav-item text-center"><a class="nav-link text-light" href="{% url 'Home:logout' %}">Cerrar Sesión</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

apps/home/templates/home/register.html
{% extends 'Home/base.html' %}

{% block TITULO %}
    <h1>Registro de Usuario</h1>
{% endblock TITULO %}

{% block BODY %}
    <form method="post" class="formulario">
        {% csrf_token %}
        {{form.as_p}}

        <button class="btn btn-success" type="submit">Registrar Usuario</button>
    </form>
    <style>
        .formulario {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        }
        input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;
            transition: background-color 0.3s;
        }
        .btn:hover {
            background-color: #45a049;
        }
    </style>
    <br>
    
{% endblock BODY %}

apps/home/templates/home/tiendas.html
{% load static %}

<h1 class="text-center">NUESTRAS TIENDAS</h1>
<div class="accordion" id="accordionExample">
    <style> .accordion{ padding: 0px 120px; } </style>
    <style> .img-fluid{ max-width: 60% }</style>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button bg-dark text-warning" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Tienda Santiago
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Ubicado en pleno centro de Santiago,</strong> ofrecemos variedad de abarrotes, bebidas, frutas y verduras, lacteos, dulces, entre otros.
          <p><b>Horarios:</b>
            <br>Lunes a Viernes: 9:00 a 19:00 hrs
            <br>Sábados: 10:00 a 18:00 hrs
            <br>Domingos: 11:00 a 17:00 hrs</p>
          <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{% static 'Home/img/local1.png' %}">
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed bg-dark text-warning" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Tienda Puerto Montt
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Ubicado a pasos del puerto de la ciudad,</strong> ofrecemos variedad de abarrotes, bebidas, frutas y verduras, lacteos, dulces, entre otros.
          <p><b>Horarios:</b>
            <br>Lunes a Viernes: 8:30 a 19:00 hrs
            <br>Sábados: 9:00 a 20:00 hrs
            <br>Domingos: 10:00 a 17:00 hrs</p>
          <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{% static 'Home/img/local2.png' %}">
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed bg-dark text-warning" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Tienda Viña Del Mar
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>Ubicado en la costanera, </strong> ofrecemos variedad de abarrotes, bebidas, frutas y verduras, lacteos, dulces, entre otros.
          <p><b>Horarios:</b>
            <br>Lunes a Viernes: 8:30 a 22:30 hrs
            <br>Sábados: 9:30 a 22:00 hrs
            <br>Domingos: Cerrado</p>
          <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{% static 'Home/img/local3.png' %}">
        </div>
      </div>
    </div>
  </div>