_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", include("home.urls")),
    path("productos/", include("productos.urls")),
    path("usuarios/", include("usuarios.urls")),
    path("carrito/", include("carrito.urls")),
]

######### PARA IMAGENES

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/carrito/urls.py
from django.urls import path
    #! Include sirve para traer URLS de las apps
from . import views

app_name = "carrito"

urlpatterns = [
    path("", views.carrito, name="index"),
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar_producto"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar_producto"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar_producto"),
    path("limpiar/", views.limpiar_carrito, name="limpiar_carrito"),
    path("enviar/", views.enviar_correo, name="enviar_correo"),
] 

apps/productos/urls.py
from django.urls import path
    #! Include sirve para traer URLS de las apps
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from . import views

app_name = "productos"

urlpatterns = [
    path("", views.index, name="index"),
    # path("", TemplateView.as_view(template_name="productos/index.html"), name="home"),

    path("ingresar_productos", views.ingreso_productos, name="ingresar_productos"),
    path('buscar_productos/', views.buscar_productos, name='buscar_productos'),
    ## Categorias
    path("categoria/list/", views.CategoriaList.as_view(), name="categoria_list"),
    path('categoria/create', views.CategoriaCreate.as_view(), name="categoria_create"),
    path('categoria/details/<int:pk>', views.CategoriaDetail.as_view(), name='categoria_details'),
    path('categoria/update/<int:pk>', views.CategoriaUpdate.as_view(), name='categoria_update'),
    path('categoria/delete/<int:pk>', views.CategoriaDelete.as_view(), name='categoria_delete'),

    ### Productos
    path("productos/list/", views.ProductosList.as_view(), name="productos_list"),
    path('productos/create', views.ProductosCreate.as_view(), name="productos_create"),
    path('productos/details/<int:pk>', views.ProductosDetail.as_view(), name='productos_details'),
    path('productos/update/<int:pk>', views.ProductosUpdate.as_view(), name='productos_update'),
    path('productos/delete/<int:pk>', views.ProductosDelete.as_view(), name='productos_delete'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/productos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Categoria (models.Model):
    nombre = models.CharField(max_length=20, null=False)
    descripcion = models.CharField(max_length=20, null=True)
    imagen = models.ImageField(upload_to="imgprod",blank=False, null=True)

    def __str__(self):
        return self.nombre
        

class Productos(models.Model):
    nombre = models.CharField(max_length=50, null=False)
    precio = models.PositiveIntegerField(null=False)
    cantidad = models.PositiveIntegerField(null=False)
    fecha_ingreso = models.DateField(default=timezone.now, null=False)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    umbral_minimo = models.PositiveIntegerField(null=True, blank=False)
    imagen = models.ImageField(upload_to="imgprod",blank=False, null=True)
    
    def __str__(self):
        return f'{self.nombre} - ${self.precio}.'
    

apps/productos/forms.py
from django import forms
from . import models

class ProductosForm(forms.ModelForm):
    class Meta:
        model = models.Productos
        fields = ["nombre", "precio", "cantidad", "fecha_ingreso", "categoria", "umbral_minimo", "imagen"]

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = models.Categoria
        fields = "__all__"

apps/productos/views.py
from django import forms
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from .models import Productos
from django.http import HttpRequest, HttpResponse

from .forms import ProductosForm
from .forms import CategoriaForm
from . import models

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.core.mail import send_mail

def index(request):
    productos_registrados = Productos.objects.all()
    contexto = {"productos": productos_registrados}
    return render(request, "productos/index.html", contexto)


####### Formulario Ingresar Productos###
def ingreso_productos(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ProductosForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("productos:home")
    else:
        form = ProductosForm()
    return render(request, "productos/ingresar_productos.html", {"form": form})

####### Busqueda de Productos ####
def buscar_productos(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        # Obtener el término de búsqueda del formulario
        termino_busqueda = request.POST.get('termino_busqueda')
        # Realizar la búsqueda en la base de datos
        productos = Productos.objects.filter(nombre__icontains=termino_busqueda)
        # Pasar los resultados de la búsqueda al contexto
        context = {'productos': productos}
        return render(request, 'productos/buscar_productos.html', context)
    else:
        return render(request, 'productos/buscar_productos.html')
    
## Clase Listar Categorias
class CategoriaList(ListView):
    model = models.Categoria

## Clase Crear Categorias
class CategoriaCreate(CreateView):
    model = models.Categoria
    form_class = CategoriaForm
    success_url = reverse_lazy("productos:categoria_list")

### Clase Ver Detalles Categorias
class CategoriaDetail(DetailView):
    model = models.Categoria

# Clase Actualizar Categorias
class CategoriaUpdate(UpdateView):
    model = models.Categoria
    form_class = CategoriaForm
    success_url = reverse_lazy("productos:categoria_list")

# Clase Eliminar Categorias
class CategoriaDelete(DeleteView):
    model = models.Categoria
    success_url = reverse_lazy("productos:categoria_list")

# ---------------------------------------#

## Clase Listar Productos
class ProductosList(ListView):
    model = models.Productos

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Productos.objects.filter(nombre__icontains = consulta)
        else:
            object_list = models.Productos.objects.all()
        return object_list ## Es un objeto Query Set

## Clase Crear Productos
class ProductosCreate(CreateView):
    model = models.Productos
    form_class = ProductosForm
    success_url = reverse_lazy("productos:productos_list")

### Clase Ver Detalles Productos
class ProductosDetail(DetailView):
    model = models.Productos

# Clase Actualizar Productos
class ProductosUpdate(UpdateView):
    model = models.Productos
    form_class = ProductosForm
    success_url = reverse_lazy("productos:productos_list")

# Clase Eliminar Productos
class ProductosDelete(DeleteView):
    model = models.Productos
    success_url = reverse_lazy("productos:productos_list")


def enviar_notificacion_stock_bajo(producto):
    subject = 'Notificación de stock bajo'
    message = f'El stock del producto {producto.nombre} ha caído por debajo del umbral mínimo.\nEl stock actual es de: {producto.cantidad} \n\n ¡Reabastece este producto!'
    from_email = 'minimarket.lostios@gmail.com' 
    recipient_list = ['minimarket.lostios@gmail.com']  # Correo del destinatario

    # Envio del correo electrónico
    send_mail(subject, message, from_email, recipient_list, fail_silently=False)

apps/productos/templates/productos/buscar_productos.html
{% extends 'Home/base.html' %}

{% block BODY %}
    <!-- Buscar Producto -->
    <form class="text-center " method="post">
        {% csrf_token %}
        <input type="text" name="termino_busqueda" placeholder="Buscar tu producto...">
        <button type="submit">Encuéntrame</button>
        <p></p>
    </form>

    <!-- Resultado Busqueda -->
    <div class="row gx-4 gx-lg-5 justify-content-center">
        {% if productos %}
            {% for producto in productos %}
                {% include 'Home/card.html' with card=producto.nombre card_precio=producto.precio card_categoria=producto.categoria card_imagen=producto.imagen %}
                {% if producto.imagen %}
                    <img src="{{producto.imagen.url}}">                    
                {% endif %}
            {% endfor %}
        {% else %}
        <p></p>
        <h3 class="text-center text-danger ">No se encontraron resultados. <br>Favor ingresa un producto.</h3>
        {% endif %}
    </div>
  
{% endblock BODY %}

apps/productos/templates/productos/categoria_confirm_delete.html
{% extends 'productos/index.html' %}

{% block TITULO %}
<h1>Eliminación de Categorías de Productos</h1>
{% endblock TITULO %}

{% block BODY %}
    <div class="justify-content-center m-5">
        <p class="fs-5 fst-italic ">¿Confirma eliminar "{{object}}"?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger ">Confirmar</button>
        </form>
    </div>

    <div class="d-flex justify-content-center ">
        <button class="btn btn-outline-info "><a class="nav-link text-dark text-center" href="{% url 'productos:categoria_list' %}">Volver atrás</a></button>
    </div>
{% endblock BODY %}

apps/productos/templates/productos/categoria_detail.html
{% extends 'productos/index.html' %}

{% block TITULO %}
    <h1>Detalle Categorías de Productos</h1>
{% endblock TITULO %}

{% block BODY %}
<div class="d-flex justify-content-center">
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div>
            <div class="card h-100 m-2">
                <div class="card-body bg-black">
                    <h2 class="card-title text-light">{{categoria.nombre}} </h2>
                    <h5 class="card-text text-warning">{{categoria.descripcion}}</h5>
                    <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{{object.imagen.url}}" alt="Imagen"></img>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center ">
    <button class="btn btn-outline-info "><a class="nav-link text-dark text-center" href="{% url 'productos:categoria_list' %}">Volver atrás</a></button>
</div>
{% endblock BODY %}

apps/productos/templates/productos/categoria_form.html
{% extends 'productos/index.html' %}

{% block TITULO %}
<h1>Crear/Actualizar Categoría de productos</h1>
{% endblock TITULO %}

{% block BODY %}
<br>
    <form method="post" class="formulario">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success ">Guardar</button>
    </form>
<br>
    <style>
        .formulario {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        }
        .form-group {
            margin-bottom: 20px;
            }

        input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;
            transition: background-color 0.3s;
        }
        .btn:hover {
            background-color: #45a049;
        }
    </style>
{% endblock BODY %}

apps/productos/templates/productos/categoria_list.html
{% extends 'productos/index.html' %}

{% block TITULO %}
    <h1>Lista de Categorías de productos</h1>
{% endblock TITULO %}

{% block BODY %}

<div class="row justify-content-center">
    {% if object_list %}
        {% for categoria in object_list %}
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="card h-100 m-2">
                    <div class="card-body bg-black">
                        <h2 class="card-title text-light">{{categoria.nombre}} </h2>
                        <h6 class="card-text text-warning">{{categoria.descripcion}}</h6>
                        <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{{categoria.imagen.url}}" alt="Imagen"></img><br>
                        <div class="text-center">
                            <a href="{% url 'productos:categoria_details' categoria.id %}" class="btn btn-success">Ver Detalles</a>
                            <a href="{% url 'productos:categoria_update' categoria.id %}" class="btn btn-primary">Actualizar</a>
                            <a href="{% url 'productos:categoria_delete' categoria.id %}" class="btn btn-danger">Eliminar</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>no hay elementos</p>
    {% endif %}
</div>
<br>

{% endblock BODY %}

apps/productos/templates/productos/index.html
{% extends 'Home/base.html' %}

{% block TITULO %}
<h1>Productos</h1>
{% endblock TITULO %}
{% block BODY %}
    <div class="row justify-content-center">
            {% for producto in productos %}
            <div class="col-sm-6 col-md-4 col-lg-3">
                {% include 'Home/card.html' with card=producto.nombre card_precio=producto.precio card_categoria=producto.categoria card_imagen=producto.imagen.url %}
            </div>
            {% endfor %}
    </div>

    <div class="w-75 mx-auto">
        <div class="alert alert-primary text-center" role="alert">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="row" colspan="4" class="text-center">CARRITO</th>
                    </tr>
                    <tr>
                        <th scope="col">NOMBRE</th>
                        <th scope="col">PRECIO</th>
                        <th scope="col">CANTIDAD</th>
                        <th scope="col">SUBTOTAL</th>
                    </tr>
                </thead>
                <tbody>
                    {% if request.session.carrito.items %}
                    {% for key, value in request.session.carrito.items %}
                    <tr>
                        <td>{{ value.nombre }}</td>
                        <td>$ {{ value.precio }}</td>
                        <td>
                            <a href="{% url 'carrito:agregar_producto' value.producto_id %}"
                                class="badge btn btn-primary badge-dark">+</a>
                            {{ value.cantidad }}
                            <a href="{% url 'carrito:restar_producto' value.producto_id %}"
                                class="badge btn btn-danger badge-dark">-</a>
                        </td>
                        <td>$ {{ value.acumulado }}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="4">
                            <div class="alert alert-danger text-center">Sin Productos</div>
                        </td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">Total: </th>
                        <td colspan="3" class="text-center"><strong>$ {{ total_boleta }}</strong></td>
                        {% if mensaje %}
                            <h3 class="text-danger ">{{ mensaje }}</h3>
                            <a href="{%url 'productos:index' %}"><button class="btn btn-primary">Ver Otros Productos</button></a>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
            <div class="row text-center">
                <div class="col-md-6 alert alert-success ">
                    <a href="{% url 'carrito:limpiar_carrito' %}" class="btn btn-danger btn-block">Vaciar Carrito</a>
                </div>
                <div class="col-md-6 alert alert-success text-center">
                    <form method="post" action="{% url 'carrito:enviar_correo' %}">
                        {% csrf_token %}
                        <input type="email" placeholder="Ingresa tu correo" name="correo" required>

                        <div class="g-recaptcha d-flex justify-content-center " data-sitekey="6Lc7-RMpAAAAAFkDWJvme1xDA_kwTnSpTvEeCGFm"></div>
                        <button type="submit" class="btn btn-success btn-block">Enviar Solicitud</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock BODY %}

apps/productos/templates/productos/productos_confirm_delete.html
{% extends 'productos/index.html' %}

{% block BODY %}
    <h1>Eliminación de Productos</h1>

    <p class="fs-5 fst-italic ">¿Confirma eliminar "{{producto}}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger ">Confirmar</button>
    </form>

    <div class="d-flex justify-content-center ">
        <button class="btn btn-outline-info "><a class="nav-link text-dark text-center" href="{% url 'productos:productos_list' %}">Volver atrás</a></button>
    </div>
{% endblock BODY %}

apps/productos/templates/productos/productos_detail.html
{% extends 'productos/index.html' %}

{% block TITULO %}
    <h1>Detalle de Productos</h1>
{% endblock TITULO %}

{% block BODY %}
<div class="d-flex justify-content-center">
    <div class="col-sm-6 col-md-4 col-lg-3">
        <div>
            <div class="card h-100 m-2">
                <div class="card-body bg-black">
                    <h2 class="card-title text-light">{{object.nombre}} </h2>
                    <h6 class="card-text text-warning">{{object.categoria}}</h6>
                    <h3 class="card-text text-warning">${{object.precio}}</h3>
                    <h3 class="card-text text-warning text-center">Stock: {{object.cantidad}}</h3>
                    <h3 class="card-text text-light text-center">Fecha de ingreso: <br> {{object.fecha_ingreso}}</h3>
                    <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{{object.imagen.url}}" alt="Imagen"></img>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center ">
    <button class="btn btn-outline-info "><a class="nav-link text-dark text-center" href="{% url 'productos:productos_list' %}">Volver atrás</a></button>
</div>


{% endblock BODY %}

apps/productos/templates/productos/productos_form.html
{% extends 'productos/index.html' %}

{% block TITULO %}
    <h1>Crear/Actualizar Productos</h1>
{% endblock TITULO %}

{% block BODY %}
<p></p>
    <div class="formulario">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{form.as_p}}
            </div>
            <button type="submit" class="btn btn-outline-primary ">Guardar</button>
        </form>
        <style>
            .formulario {
                max-width: 400px;
                margin: 0 auto;
                padding: 20px;
                background-color: #fff;
                border-radius: 5px;
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
            }

            .form-group {
                margin-bottom: 20px;
            }

            input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ccc;
                border-radius: 4px;
            }

            .btn {
                display: block;
                width: 100%;
                padding: 10px;
                background-color: #4CAF50;
                color: #fff;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                font-weight: bold;
                transition: background-color 0.3s;
            }

            .btn:hover {
                background-color: #45a049;
            }
        </style>
    </div>
    <p></p>
{% endblock BODY %}

apps/productos/templates/productos/productos_list.html
{% extends 'productos/index.html' %}

{% block TITULO %}
    <h1>Listar Productos</h1>
{% endblock TITULO %}

{% block BODY %}
    <div class="py-lg-4 text-center">
        <form action="{% url 'productos:productos_list' %}" method="get">
            <input type="text" name="consulta" placeholder="Busca un producto...">
        </form>
    </div>

    {% if object_list %}
    <div class="row justify-content-center ">
        {% for object in object_list %}
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div>
                    <div class="card h-100 m-2">
                        <div class="card-body bg-black">
                            <h2 class="card-title text-light">{{object.nombre}} </h2>
                            <h6 class="card-text text-warning">{{object.categoria}}</h6>
                            <h3 class="card-text text-warning text-center">${{object.precio}}</h3>
                            <img class="img-fluid img-thumbnail rounded mx-auto d-block" src="{{object.imagen.url}}" alt="Imagen"></img><br>
                            <div class="text-center">
                                <a href="{% url 'productos:productos_details' object.id %}" class="btn btn-success">Ver Detalles</a>
                                <a href="{% url 'productos:productos_update' object.id %}" class="btn btn-primary ">Actualizar</a>
                                <a href="{% url 'productos:productos_delete' object.id %}" class="btn btn-danger">Eliminar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
    <p>no hay elementos</p>
    {% endif %}
    </div>


{% endblock BODY %}